version: '3'
services:
  pgbd:
    image: "postgres:11"
    container_name: "pgbd"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=1
    ports:
      - "54320:5432"
    volumes:
      - //d/bd/data:/var/lib/postgresql/data